name: Build LaTeX document
on: 
    push:
        paths: 
            - report/**
            - .github/workflows/**
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: FiraCode.ttf
      - name: Copy
        run: mkdir build && cp ./main.pdf ./build/main.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: build/main.pdf
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: build
          GIT_CONFIG_NAME: oathompsonjones
          GIT_CONFIG_EMAIL: oathompsonjones@gmail.com